# Generated by Django 4.2 on 2025-03-12 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
            ],
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='file_format',
            field=models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX'), ('PPTX', 'PPTX'), ('TXT', 'TXT'), ('PNG', 'PNG'), ('JPG', 'JPG'), ('HEIC', 'HEIC')], default='PDF', max_length=10),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='vote',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='materials.studymaterial'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'material')},
        ),
    ]
