# Generated by Django 4.2 on 2025-03-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_vote_studymaterial_file_format_delete_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='university',
        ),
    ]
