# Generated by Django 4.2 on 2025-03-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_remove_lecturer_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='file_format',
            field=models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX'), ('PPTX', 'PPTX'), ('TXT', 'TXT'), ('PNG', 'PNG'), ('JPG', 'JPG'), ('JPEG', 'JPEG'), ('HEIC', 'HEIC')], default='PDF', max_length=10),
        ),
    ]
