# Generated by Django 4.2 on 2025-03-14 14:05

import apps.materials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_studymaterial_file_format'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='file_format',
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/', validators=[apps.materials.models.validate_material_extension, apps.materials.models.validate_file_size]),
        ),
    ]
