# Generated by Django 4.2 on 2025-03-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_alter_vote_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='materials',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='tags',
            field=models.ManyToManyField(blank=True, max_length=255, related_name='study_mater_of_tag', to='materials.tag'),
        ),
    ]
