# Generated by Django 4.2 on 2025-03-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chatmessage_group_alter_chatmessage_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver',
        ),
    ]
