# Generated by Django 4.2 on 2025-03-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_favorite_lecturer_alter_user_favorite_subjects_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorite_lecturer',
            new_name='favorite_lecturers',
        ),
    ]
