# Generated by Django 4.2 on 2025-03-13 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_vote_studymaterial_file_format_delete_like_and_more'),
        ('users', '0003_rename_favorite_lecturer_user_favorite_lecturers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_lecturers',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_lecturers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoriting_users', to='materials.lecturer'),
        ),
    ]
