# Generated by Django 4.2 on 2025-03-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_favorite_lecturers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorite_lecturers',
            new_name='favorite_lecturer',
        ),
    ]
