# Generated by Django 4.2 on 2025-03-14 14:05

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_favorite_lecturers_user_favorite_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='users/', validators=[apps.users.models.validate_avatar_extension, apps.users.models.validate_file_size]),
        ),
    ]
